Sprint 2/enemy attack
RohitK-RIT/Flux-TimesUp pull request #6
Opened 2024-10-10 15:54 UTC by roosa2000

## Summarize what is being added

Implemented Player Detection in a Conical field of View Angle

## Please describe how to test

- In the scenes folder open the enemy_10.3 scene.

- Play the scene.

- Move the player around.

- The enemy would rotate towards the player only when the player is in front of the enemy and within the detection range.

- It should not be rotating or detecting the player if the player is behind or not in the conical field of view angle.

## Issue worked on

https://timeisup.atlassian.net/browse/SCRUM-18?atlOrigin=eyJpIjoiOTI0OTE4MDA5MGRmNDkxMDg5MjRjY2UyNzUyYzRlMGMiLCJwIjoiaiJ9

## What Sprint is this due in?

Sprint 2

2024-10-13 19:33 UTC, RohitK-RIT requested changes
Your PR has a few issues:

- [x] Merges into the main should merge in sprint 2.
- [x] Rebase your code on the sprint 2 branch.
- [ ] Structural changes (as discussed)

2024-10-19 22:56 UTC, RohitK-RIT approved these changes, later dismissed
Clamped the weapon pitch angle

2024-10-19 23:09 UTC, heenathadani submitted a review, later dismissed

2024-10-19 23:54 UTC, RohitK-RIT approved these changes, later dismissed

2024-10-19 23:54 UTC, heenathadani approved these changes

2024-10-19 23:55 UTC, RohitK-RIT submitted a review, later dismissed

2024-10-19 23:55 UTC, heenathadani submitted a review, later dismissed

2024-10-19 23:55 UTC, shinzozs submitted a review, later dismissed

2024-10-20 00:13 UTC, Tico39 approved these changes

2024-10-20 00:17 UTC, merged